services:
  backend:
    build: ./back
    ports:
      - "8000:8000"
    command: >
      bash -c "
      aerich init-db
      && aerich migrate
      && aerich upgrade
      && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/mydb
    volumes:
      - ./back:/app
    restart: always

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./front:/app
    environment:
      REACT_APP_API_URL: http://localhost:8000
    restart: always

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flower_store
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
